# Generated by Django 5.0.2 on 2024-02-14 06:51

import datetime
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_visit_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.TimeField(),  # or models.DateTimeField if that's what you want in 0006
        ),
    ]
