# Generated by Django 5.0.2 on 2024-02-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_visit_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.TimeField(),
        ),
    ]
