# Generated by Django 5.0.2 on 2024-02-14 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_visit_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
